services:
  anomaly-ai-backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/models
      - ./backend/data:/app/data
    environment:
      - APP_ENV=development
      - PYTHONPATH=/app/src
      - MODEL_DIR=/app/models
      - DATA_DIR=/app/data

  anomaly-ai-frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - anomaly-ai-backend
